version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      LANG: C.UTF-8
    volumes:
      - ./db/mysql/volumes:/var/lib/mysql

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db